language: php

matrix:
  include:
    - php: 7.2
      env: ILLUMINATE_VERSION=6.0
    - php: 7.2
      env: ILLUMINATE_VERSION=6.*
php:
  - 7.2

sudo: false

before_install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --testdox
